services:
  postgres:
    image: postgres:15
    container_name: apple-postgres
    restart: always
    environment:
      POSTGRES_DB: leafsnap
      POSTGRES_USER: leafsnap_user
      POSTGRES_PASSWORD: T0fEiuzSqaIpEeMd7QS2MYjfsZD4UZMA
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U leafsnap_user"]
      interval: 5s
      timeout: 5s
      retries: 5

  ml:
    build: ./ml
    container_name: apple-ml
    restart: always
    ports:
      - "5000:5000"

  backend:
    build: ./apple-disease-backend
    container_name: apple-backend
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      ml:
        condition: service_started
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://apple-postgres:5432/leafsnap
      SPRING_DATASOURCE_USERNAME: leafsnap_user
      SPRING_DATASOURCE_PASSWORD: T0fEiuzSqaIpEeMd7QS2MYjfsZD4UZMA
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      ML_API_URL: http://apple-ml:5000/predict

  frontend:
    build: ./apple-disease-frontend2
    container_name: apple-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
